### ISSUE TITLE
License or privilege error

### ISSUE THREAD

**Issue by floreagyorgy** [miyako/4d-plugin-sign-pdf-versy#2]
Hello Miyako,
I would like to deploy your plugin with a 4D v17.4 merged 64 bit application on Mac OS. It works fine on Mac OS 14 Mojave and 15 Catalina, but not at all on any earlier Mac OS (version 10 - 13).
Is there any solution for older Macs?
Thank you in advance

George Flórea
CiPOsoft Ltd.
Hungary

**Comment by miyako** [comment]
You might need to compile from scratch, using an older SDK, on an older Mac.
Not just the plugin, but the linked libraries too.
Needless, you would have to install an older Xcode for that.

**Comment by floreagyorgy** [comment]
Hi Miyako,
Thank you very much for your immediat answer.
Actually, I tried already what you suggested, but it failed. I opened with Xcode 9.3 the VersyPDF.v9.xcodeproj under Mac OS 13, made some build settings, but the build process was failed. Do I miss something?

![Képernyőfotó 2020-06-03 - 13 30 05](https://user-images.githubusercontent.com/51167084/83634351-b0570780-a5a2-11ea-9624-1aaeecc79bfe.png)

![Képernyőfotó 2020-06-03 - 13 31 04](https://user-images.githubusercontent.com/51167084/83634384-c06ee700-a5a2-11ea-90a9-56f503ecc78a.png)

Thank you in advance
George Flórea
CiPOsoft Ltd.
Hungary

**Comment by miyako** [comment]
The error message says it all.

The v9 project is just a stating point, you will have to add more files and settings to make it work.

For instance, you will have to add the C_TEXT.cpp and C_TEXT.h files, change the document property for the former to "objective-cpp" (because the file uses some obj-c; the extension could be mm, but then I will have trouble on Windows), and so on.

But I would rather not engage in a step-by-step guide on how to use Xcode.

**Comment by miyako** [comment]
To be clear, the "basic" v9 file is **automatically** generated, but I never complete the project **manually** to the point that it can actually build a product, since I can not use Xcode 9 on my work computer any more.

**Comment by floreagyorgy** [comment]
Dear Miyako,
Thank you very much for your answer. It is roughly clear for me now, that I will rather give up the support of older Macs. Thank you again for your time.
George
